version: '2'

services:

  service:
    build: ./WS-movies
    command: python ./WS-movies/app.py runserver 0.0.0.0:81
    ports:
      - "81:5000"
    volumes:
      - .:/code

  tickets:
    build: .
    command: python3 tickets_stat.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - service